config/routes.rb
OmniApp::Application.routes.draw do

  match '/users/updateSurvey',      to: 'users#updateSurvey',        via: 'post'

  match '/users/updateGenre', to: 'users#updateGenre', via: 'post'

  match '/users/updateInfluence', to: 'users#updateInfluence', via: 'post'

  match '/users/addMedia', to: 'users#addMedia', via: 'post'

  match '/users/editSurvey',      to: 'users#editSurvey',        via: 'post'

  match '/users/create_event',      to: 'users#create_event',        via: 'post'

  resources :users

  post "/users/save_user_location" => 'users#save_user_location', :as => :save_user_location
  get  'edit' => 'users#edit'
  get  'edit2' => 'users#edit2'
  post "users/matchChoice"
  get 'view_matches' => 'users#view_matches'
  get 'events' => 'users#get_local_events'
  get 'user_events' => 'users#get_user_events'
  get 'add_event' => 'users#add_event'

=begin
  get "users/new"             # Currently empty; exists only to pass users/new test

  get "/users" => "users#index"
  get "/users/:id" => "users#show"
  get "/users/new" => "users#new"
  post "/users" => "users#create"  # usually a submitted form
  get "/users/:id/edit" => "users#edit"
  put "/users/:id" => "users#update" # usually a submitted form
  delete "/users/:id" => "users#destroy"
=end

  root               'home#home'
  get     'about'    => 'home#about'
  get     'profile'  => 'users#show'
  get     'matching' => 'users#findMatch', :as => :find_match
  get     'testmatching' => 'users#testFindMatch', :as => :testFindMatch

  get     'users/:id/matches'  => 'users#showMatches', :as => :user_matches
  get     "users/:id/messagesList" =>  'users#showMsgList', :as => :messages_list
  get     'users/:id/messages'  => 'users#showMatchMsgs', :as => :user_match_msg
  get     'users/:ids/groupsMessages' =>  'users#showGroupMsgs', :as => :group_msgs
  post    "users/:id/createChat" => 'users#createChat', :as => :create_chat
  post    "users/:ids/createGroupChat" => 'users#createGroupChat', :as => :create_group_chat
  post    "users/newChat" => 'users#newChat', :as => :new_chat

  get 'auth/:provider/callback', to: "sessions#create"

  get 'sign_out', to: "sessions#destroy", as: 'sign_out'

end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_messageable


  has_many :instruments
  has_many :genres
  has_many :influences
  has_many :mediums
  has_many :matchings
  has_many :chats, dependent: :delete_all
  has_many :groups, dependent: :delete_all
  has_many :events

  def self.sign_in_from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end

  def self.create_user_from_omniauth(auth)
    create(
        provider: auth['provider'],
        uid: auth['uid'],
        name: auth['info']['name'],
        image: auth['info']['image'],
        email: auth['info']['email']
    )
  end

  def self.update_bio(uid, bio)
    user = self.find(uid)
    user.bio = bio
    user.save
  end

  def self.update_radius(uid, radius)
    user = self.find(uid)
    user.radius = radius
    user.save
  end

  def self.getDistance(loc1, loc2)
    rad_per_deg = Math::PI/180  # PI / 180
    rkm = 6371                  # Earth radius in kilometers
    rm = rkm * 1000             # Radius in meters

    dlat_rad = (loc2[0]-loc1[0]) * rad_per_deg  # Delta, converted to rad
    dlon_rad = (loc2[1]-loc1[1]) * rad_per_deg

    lat1_rad, lon1_rad = loc1.map {|i| i * rad_per_deg }
    lat2_rad, lon2_rad = loc2.map {|i| i * rad_per_deg }

    a = Math.sin(dlat_rad/2)**2 + Math.cos(lat1_rad) * Math.cos(lat2_rad) * Math.sin(dlon_rad/2)**2
    c = 2 * Math::atan2(Math::sqrt(a), Math::sqrt(1-a))

    return rm * c # Delta in meters
  end

  # Add function to add interest_level
  def self.update_interest_level(uid, interest_level)
    user = self.find(uid)
    user.interest_level = interest_level
    user.save

  end

end

app/controllers/users_controller.rb
require 'json'
require 'open-uri'

class UsersController < ApplicationController
  protect_from_forgery except: [:showMatchMsgs, :save_user_location]
  skip_before_filter :verify_authenticity_token

  @neo = Neography::Rest.new("http://neo4j:arbor94@localhost.com:7474")

  def index

  end

  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create

  end

  def edit
    @user = User.find(session[:user_id])
    #@instruments = InstrumentChoice.all       # todo: add all instrument choices to this database
                                              # then have for loop creating checkboxes in _form.html.erb
  end


  def edit2
    @user = User.find(session[:user_id])
    @user_instruments = [false, false, false, false, false]
    @user_looking = [false, false, false, false, false]
    @user.instruments.each do |i|
      if i.play == true
        if i.instrument == 'Guitar'
          @user_instruments[0] = true
        elsif i.instrument == 'Bass'
          @user_instruments[1] = true
        elsif i.instrument == 'Vocals'
          @user_instruments[2] = true
        elsif i.instrument == 'Drums'
          @user_instruments[3] = true
        elsif i.instrument == 'Keyboard'
          @user_instruments[4] = true
        end
      elsif i.play == false   # User does not play but is searching for this instrument
        if i.instrument == 'Guitar'
          @user_looking[0] = true
        elsif i.instrument == 'Bass'
          @user_looking[1] = true
        elsif i.instrument == 'Vocals'
          @user_looking[2] = true
        elsif i.instrument == 'Drums'
          @user_looking[3] = true
        elsif i.instrument == 'Keyboard'
          @user_looking[4] = true
        end
      end
    end
  end

  def update
  end

  def updateSurvey
    puts params
    params[:play] = 1
    params[:uid] = session[:user_id]
    # loop through all checkboxes checked for instruments user plays
    # creates entry in Instrument database with plays=1
    params[:instrument].each do |i|
      Instrument.add(i, 1, 1, params[:uid])   # todo: replace paramas with real values for experience and plays
    end
    # loop through all checkboxes checked for instruments user is looking for
    # creates entry in Instrument database with plays=0
    params[:looking].each do |l|
      Instrument.add(l, 1, 0, params[:uid])
    end
    # creating genre entry for each genre checked
    params[:genre].each do |g|
      Genre.add(g, params[:uid])
    end
    influences = params[:influence].split(',')
    influences.each do |i|
      genres = get_genre_from_influence(i)
      Influence.add(i, params[:uid], genres)
    end
    if params[:url] != ''
      if params[:url].include? "youtube"
        media = Medium.add(params, 'youtube')
      elsif params[:url].include? "soundcloud"
        media = Medium.add(params, 'soundcloud')
      end
    end
    User.update_bio(session[:user_id], params[:bio])
    User.update_interest_level(session[:user_id], params[:interest_level])
    User.update_radius(session[:user_id], params[:radius])
    redirect_to action: "show", id: session[:user_id]
  end

  def editSurvey
    puts params
    params[:uid] = session[:user_id]
    uid = session[:user_id]
    user = User.find(session[:user_id])
    Instrument.delete_all(uid)
    params[:instrument].each do |i|
      Instrument.add(i, 1, 1, uid)   # todo: replace params with real values for experience and plays
    end
    params[:looking].each do |l|
      Instrument.add(l, 1, 0, uid)
    end
    Genre.delete_all(uid)
    params[:genre].each do |g|
      Genre.add(g, uid)
    end
    influences = params[:influence].split(',')
    influences.each do |i|
      genres = get_genre_from_influence(i)
      Influence.add(i, params[:uid], genres)
    end
    User.update_bio(uid, params[:bio])
    User.update_interest_level(uid, params[:interest_level])
    User.update_radius(uid, params[:radius])
    Medium.delete_all(uid)

    if params[:url] != ''
      if params[:url].include? "youtube"
        media = Medium.add(params, 'youtube')
      elsif params[:url].include? "soundcloud"
        media = Medium.add(params, 'soundcloud')
      end
    end

    redirect_to action: "show", id: session[:user_id]
  end

  # Finds a possible match for swiping
  def findMatch


    allU = User.all.where("id != ?", current_user.id)
    closeU = [], elligibleU = []
    myLookingForInstruments = [], myInstruments = [],  myGenres = []
    sorted = Hash.new

    #GET INSTRUMENTS CURRENT USER WANTS AND PLAYS
    current_user.instruments.each do |inst|
      if !inst.play
        myLookingForInstruments.append(inst.instrument)
      else
        myInstruments.append(inst.instrument)
      end
    end

    #GET GENRES CURRENT USER PLAYS
    current_user.genres.each do |g|
      myGenres.append(g.genre)
    end
    allU.each do |user|
      if Matching.ifElligible(current_user.id.to_s, user)
        elligibleU.append(user)
      end
    end

    #START GETTING POINTS
    elligibleU.each do |user|
      score = 0
      #  FIRST CHECK TO SEE IF MATCH IS USER'S RADIUS
      #if User.getDistance([current_user.lat, current_user.long], [user.lat, user.long]) <= current_user.radius
        userPlays = user.instruments.where("play = ?", true)
        userWants = user.instruments.where("play = ?", false)
        userGenre = user.genres

        # 1. get points for instruments and experience
        score += Matching.getInstrumentAndExperiencePoints(myLookingForInstruments, userPlays, myInstruments, userWants)

        # 2. if score = 0, then not matchable, because no instruments match. if != 0, then proceed to get other points
        if score != 0
          # 3. get genre points
          score += Matching.getGenrePoints(myGenres, userGenre)

          # 4. get influence points
          score += Matching.getInfluencePoints(current_user.influences, user.influences)
          # 5. get profile likes points

          # FINALLY add user and score to hash.
          sorted[user.id.to_s] = score
        end
      #end

    end

    users = sorted.sort_by { |user, score| score}
    if users.size() == 0
      render :no_new_users
    else
      users.each do |id, score|
        @user = User.find(id.to_i)
      end
    end


  end

  def testFindMatch
    allU = User.all
    closeU = [], elligibleU = []
    myLookingForInstruments = [], myInstruments = [],  myGenres = []
    sorted = Hash.new

    #GET INSTRUMENTS CURRENT USER WANTS AND PLAYS
    current_user.instruments.each do |inst|
      if !inst.play
        myLookingForInstruments.append(inst.instrument)
      else
        myInstruments.append(inst.instrument)
      end
    end

    #GET GENRES CURRENT USER PLAYS
    current_user.genres.each do |g|
      myGenres.append(g.genre)
    end

    #START GETTING POINTS
    allU.each do |user|
      score = 0
      #  FIRST CHECK TO SEE IF MATCH IS USER'S RADIUS
      if User.getDistance([current_user.lat, current_user.long], [user.lat, user.long]) <= current_user.radius
        userPlays = user.instruments.where("play = ?", true)
        userWants = user.instruments.where("play = ?", false)
        userGenre = user.genres

        # 1. get points for instruments and experience
        score += Matching.getInstrumentAndExperiencePoints(myLookingForInstruments, userPlays, myInstruments, userWants)

        # 2. if score = 0, then not matchable, because no instruments match. if != 0, then proceed to get other points
        if score != 0
          # 3. get genre points
          score += Matching.getGenrePoints(myGenres, userGenre)

          # 4. get influence points
          score += Matching.getInfluencePoints(current_user.influences, user.influences)
          # 5. get profile likes points

          # FINALLY add user and score to hash.
          sorted[user.id.to_s] = score
        end
      end

    end

    users = sorted.sort_by { |user, score| score}.reverse!
    @users = users
  end


  # todo: notify user that a match occured and ask
  # if they want to continue looking for users or
  # begin a message
  # Return True if user wants to begin messaging
  # false otherwise
  def notify_user_match

  end

  # Begin a message with someone matched
  def init_message

  end

  # Updates Matching object after user clicks yes or no on another user
  def matchChoice
    userID = params[:id].to_s
    meID = current_user.id.to_s


    # Find the correct match between the two users
    if Matching.where(user1: meID, user2: userID).exists?
      the_match = Matching.where(user1: meID, user2: userID).first!
    elsif Matching.where(user1: userID, user2: meID).exists?
      the_match = Matching.where(user1: userID, user2: meID).first!
    end


    # Checking if the like button or dislike button was pressed
    # in order to properly update status value
    if params.has_key?(:like)
      if !Matching.matchExists(meID, userID)
        Matching.createMatch(meID, userID, 1)
        the_match = Matching.where(user1: meID, user2: userID).first!
      else
        the_match = Matching.updateLikeStatus(the_match, meID, userID)
      end
    elsif params.has_key?(:dislike)
      if !Matching.matchExists(meID, userID)
        Matching.createMatch(meID, userID, -1)
        the_match = Matching.where(user1: meID, user2: userID).first!
      else
        the_match = Matching.updateDislikeStatus(the_match, meID, userID)
      end
    end

    # Check to see if we have a match
    if the_match.status == 3
      flash[:notice] = "You have a new match with " + User.find(params[:id]).name + "!"
    end
    redirect_to action: "findMatch" and return
  end


  def view_matches
    me = User.find(session[:user_id])
    #@matches = Matching.where("(user1 = ? OR user2 = ?) AND status = ?", me.uid, me.uid, 2)
    @matches = Matching.where('user1 = ? OR user2 = ?', me.uid, me.uid)
    @matched_users = []
    @statuses = []
    @matches.each do |match|
      if match.user1 == me.uid

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_ajaxchat.html.erb
<li class="media comment" id="myMsg">
  <%= link_to image_tag(image, alt: name, class: "media-object"),
              image, target: '_blank', class: 'pull-right' %>
  <div class="media-body" id="message">
    <h4 class="media-heading"><%= link_to name, image, target: '_blank' %>
      <small class="text-muted"> <%= created %></small></h4>
    <p><%= body %></p>
  </div>
</li>

app/views/users/_chats.html.erb
<% @chats.each do |chats| %>
    <% if current_user.id == chats.user_id %>
        <li class="media comment" id="myMsg">
          <%= link_to image_tag(chats.user.image, alt: chats.user.name, class: "media-object"),
                      user_path(chats.user_id), target: '_blank', class: 'pull-right' %>
          <div class="media-body" id="message">
            <h4 class="media-heading"><%= link_to chats.user.name, user_path(chats.user_id), target: '_blank' %>
              <small class="text-muted"> <%= chats.created_at.strftime('%-d %B %Y, %H:%M:%S') %></small></h4>
            <p><%= chats.body %></p>
          </div>
        </li>
    <% else %>
        <li class="media comment" id="matchMsg">
          <%= link_to image_tag(chats.user.image, alt: chats.user.name, class: "media-object"),
                      user_path(chats.user_id), target: '_blank', class: 'pull-left' %>
          <div class="media-body">
            <h4 class="media-heading"><%= link_to chats.user.name, user_path(chats.user_id), target: '_blank' %>
              <small class="text-muted"> <%= chats.created_at.strftime('%-d %B %Y, %H:%M:%S') %></small></h4>
            <p><%= chats.body %></p>
          </div>
        </li>
    <% end %>
<% end %>

app/views/users/_groupForm.html.erb
<div class="well">
  <%= form_for @groupChat, :url => create_group_chat_path(@groupid), remote: true do |f| %>
      <div class="form-group">
        <%= f.label :body,"Conversation here:" %>
        <%= f.text_field :body, id: "chatBody", rows: 1, cols: 20, class: 'form-control', required: true, maxlength: 2000, :placeholder => "RESPOND HERE..." %>
        <small class="label label-warning">Cannot be blank or contain more than 2000 symbols.</small>
      </div>


      <%= f.hidden_field :participants, rows: 1, class: 'form-control', required: true, maxlength: 2000, value: @groupid%>
      <%= f.submit 'Post', class: 'btn btn-primary btn-sm', id: 'msgSubmit' %>
  <% end %>
</div>

app/views/users/no_events.html.erb
<h3 class="text-center">
  <%= link_to events_path, id: "local_events" do %>Local Events <% end %>&nbsp; | &nbsp; User Events &nbsp; <a href="add_event"><span class="fa fa-plus-circle  fa-1x" aria-hidden="true"></span></a>
</h3>
<div style="width: 100%; height: 500px; padding-top: 30px; text-align: center">
  Sorry, no events found. Add your own event or come back again later!
</div>

app/views/users/no_new_users.html.erb
<div style="width: 100%; height: 500px; padding-top: 30px; text-align: center">
  Sorry, No more users in your area. Increase your radius or come back again later!
</div>

app/views/users/showMatchMsgs.js.erb
//setInterval(function() {
//   		alert("How Now Brown Cow");
// }, 5000);
console.log('helloo');

<% unless @chats.empty? %>
alert('helloo');
<% end %>

app/views/users/showMatches.html.erb
<!-- Currently just shows all users -->

<% @users.each do |user| %>

    <div class="media osw">
      <div class="media-left">
        <a href="#">
          <img class="media-object" src="<%= user.image %>" alt="...">
        </a>
      </div>
      <div class="media-body">

        <h4 class="media-heading"><%= link_to user.name, user_path(user.id) %></h4>
        <%#= link_to "MESSAGES", user_match_msg_path(user.id) %>
        <%= link_to user_match_msg_path(user.id)  do %>
            <i class="fa fa-comment fa-2x"></i>
        <% end %>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a onclick="sendCall(<%=user.id %>)" href="#" class="video"><i class="fa fa-video-camera fa-2x"></i></a>

      </div>
    </div>
<% end %>

<div hidden id="backdrop" style="position: absolute; background: #000000; top: 0; right: 0; bottom: 0; left: 0; opacity:0.7"></div>
<div hidden id="videosContainer" style="position: fixed; z-index: 10; top: 100px; width: 80%; height: 50%; margin: 0 auto; left: 0; right: 0; border: solid 3px #dc7e07; border-radius: 20px; background: #000000">
  <video id = "peerVid"  autoplay="true" style="position: relative; width: 100%; height: 100%"></video>

  <video id = "myVid" muted autoplay="true" style="position: absolute; bottom: 10px; right: 10px; width: 20%; height: 20%; border: solid 2px teal; border-radius: 5px; background: #FFFFFF"></video>

  <a href="#" id="close" style="position: absolute; top: 10px; right: 10px; color: #ff6620;">&bigotimes;</a>
</div>


<script>

  $('#videosContainer').height($('#videosContainer').width() /2);
  $(window).resize(function(){
    $('#videosContainer').height($('#videosContainer').width()/2);
  });
  //var peer = new Peer(<%= current_user.id %>, {key: 'zyjq7np7zz8y3nmi'});
  navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia  || navigator.mozGetUserMedia || navigator.msGetUserMedia;


  var myS;
  var peerS;

  $('#close').click(function() {
    $('#videosContainer').hide();
    $('#backdrop').hide();
    if(myS) {
      myS.getTracks().forEach(function (track) { track.stop(); });
    }
    else if(peerS) {
      peerS.getTracks().forEach(function (track) { track.stop(); });
    }
  });

  var peer = new Peer(<%= current_user.id %>, {host: 'mezzo-peer.herokuapp.com', secure: true, port: 443});
  peer.on('open', function(id) {
    console.log('My peer ID is: ' + id);
  });

  peer.on('connection', function(conn) {
    conn.on('open', function() {
      console.log("connection recieved from " + conn.peer);

      conn.on('data', function(data) {
        console.log("Reciever recieved data", data);
      });
    });
  });

  var errorReturnStream = function() {
    console.log("error returning stream.");
  };

  var errorSendStream = function() {
    console.log("error sending stream.");
  };
  peer.on('call', function(call) {
    console.log("getting call");
    if(navigator.getUserMedia) {
      navigator.getUserMedia({audio: true, video:true}, function(myStream) {
        myS = myStream;
        $('#videosContainer').show();
        $('#backdrop').show();
        var myvideo = document.querySelector('#myVid');
        myvideo.src = window.URL.createObjectURL(myStream);
        call.answer(myStream);
        call.on('stream', function(remoteStream) {
          peerS = remoteStream;
          console.log("remote stream returned");

          var peervideo = document.querySelector('#peerVid');
          peervideo.src = window.URL.createObjectURL(remoteStream);
        });
      }, function() {
        console.log(" error return stream");
      });
    }

  });


  function sendCall(peerID) {
    console.log("id is " + peerID);
    if(navigator.getUserMedia) {
      console.log("media exists");
      navigator.getUserMedia({audio: true, video:true}, function(myStream) {
        myS = myStream;
        $('#videosContainer').show();
        $('#backdrop').show();
        var myvideo = document.querySelector('#myVid');
        myvideo.src = window.URL.createObjectURL(myStream);
        var call = peer.call(peerID, myStream);
        call.on('stream', function(remoteStream) {
          peerS = remoteStream;
          console.log("remote stream returned");

          var peervideo = document.querySelector('#peerVid');
          peervideo.src = window.URL.createObjectURL(remoteStream);
        });
      }, function() {
        console.log("error send str");
      });


    }else {
      console.log("no media");
    }


  }//);


</script>

app/views/users/showMsgList.html.erb
<script type="text/javascript" src="../javascripts/select2.min.js"></script>
<button type="button" class="btn btn-warning btn-sm osw" data-toggle="modal" data-target="#myModal">New</button><br><br>
<%#= link_to 'New', new_chat_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal'}  %>
<div class="btn-pref btn-group btn-group-justified btn-group-lg osw" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <button type="button" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="fa fa-user" aria-hidden="true"></span>
      <div class="hidden-xs">Messages</div>
    </button>
  </div>
  <div class="btn-group osw" role="group">
    <button type="button" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="fa fa-users" aria-hidden="true"></span>
      <div class="hidden-xs">Group</div>
    </button>
  </div>
</div>

<div class="well">
  <div class="tab-content">
    <div class="tab-pane fade in active" id="tab1">
      <% @singleids.each do |id| %>
          <% user = User.find(id) %>
          <div class="media osw">
            <div class="media-left">
              <a href="#">
                <img class="media-object" src="<%= user.image %>" alt="...">
              </a>
            </div>
            <div class="media-body osw">

              <h4 class="media-heading"><%= link_to user.name, user_path(user.id) %></h4>
              <%= link_to "MESSAGES", user_match_msg_path(user.id) %>
            </div>
          </div>
      <% end %>
    </div>
    <div class="tab-pane fade in" id="tab2">
      <% @groupids.each do |ids| %>
          <% group = User.find(ids) %>
          <div class="media osw">
            <div class="media-left">
              <a href="#">
                <img class="media-object" src="<%= group[0].image %>" alt="...">
              </a>
            </div>
            <div class="media-body osw">
              <h4 class="media-heading">
                <%= group[0].name%>
                <% len = group.length - 1 %>
                <% for i in 1..len %>
                    <% unless  group[i].id == current_user.id%>
                        <%=", " + group[i].name%>
                    <% end %>
                <% end %>

                <!--VERRRYYY IMPORTANTTT!-->
                <%# @group.push(current_user).sort_by { |user| user[:id]}%>
                <% group.sort_by { |user| user[:id]}%>
                <%groupid = group[0].id.to_s%>
                <% len = group.length - 1 %>
                <% for i in 1..len %>
                    <%groupid = groupid + "," + group[i].id.to_s%>
                <% end %>
                <%#= groupid %>
              </h4>
              <%= link_to "MESSAGES", group_msgs_path(groupid) %>
            </div>
          </div>

      <% end %>
    </div>
  </div>
</div>








<!--<div>-->
  <!--<% @groupids.each do |ids| %>-->
      <!--<% group = User.find(ids) %>-->
      <!--<div class="media">-->
        <!--<div class="media-left">-->
          <!--<a href="#">-->
            <!--<img class="media-object" src="<%= group[0].image %>" alt="...">-->
          <!--</a>-->
        <!--</div>-->
        <!--<div class="media-body">-->
          <!--<h4 class="media-heading">-->
            <!--<%= group[0].name%>-->
            <!--<% len = group.length - 1 %>-->
            <!--<% for i in 1..len %>-->
                <!--<% unless  group[i].id == current_user.id%>-->
                    <!--<%=", " + group[i].name%>-->
                <!--<% end %>-->
            <!--<% end %>-->

            <!--&lt;!&ndash;VERRRYYY IMPORTANTTT!&ndash;&gt;-->
            <!--<%# @group.push(current_user).sort_by { |user| user[:id]}%>-->
            <!--<% group.sort_by { |user| user[:id]}%>-->
            <!--<%groupid = group[0].id.to_s%>-->
            <!--<% len = group.length - 1 %>-->
            <!--<% for i in 1..len %>-->
                <!--<%groupid = groupid + "," + group[i].id.to_s%>-->
            <!--<% end %>-->
            <!--<%#= groupid %>-->
          <!--</h4>-->
          <!--<%= link_to "MESSAGES", group_msgs_path(groupid) %>-->
        <!--</div>-->
      <!--</div>-->

  <!--<% end %>-->

  <!--<% @singleids.each do |id| %>-->
      <!--<% user = User.find(id) %>-->
      <!--<div class="media">-->
        <!--<div class="media-left">-->
          <!--<a href="#">-->
            <!--<img class="media-object" src="<%= user.image %>" alt="...">-->
          <!--</a>-->
        <!--</div>-->
        <!--<div class="media-body">-->

          <!--<h4 class="media-heading"><%= link_to user.name, user_path(user.id) %></h4>-->
          <!--<%= link_to "MESSAGES", user_match_msg_path(user.id) %>-->
        <!--</div>-->
      <!--</div>-->
  <!--<% end %>-->
<!--</div>-->


<div id="myModal" class="modal fade osw" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Message</h4>
      </div>
      <%= form_tag(new_chat_path, :method=>'post', :multipart => true) do %>
          <div class="modal-body">
            To: <%= text_field_tag "recipients", '', id: "chatBody", rows: 1, cols: 10, class: 'form-control', required: true %>

            Message: <%= text_field_tag "body",'', id: "chatBody", rows: 1, cols: 10, class: 'form-control', required: true, maxlength: 2000, :placeholder => "Ask to jam!" %>
            <%#= select_tag 'select', '',  class: "form-control select2-select"%>
            <div class="form-group legendary osw">
              <label class="col-md-4 control-label"> What instruments do you play?</label>
              <div class="col-md-4">
                <%= select_tag "instrument", "<option>Guitar</option>
       <option>Bass</option>
       <option>Keyboard</option>".html_safe, multiple: true, id: "selector", class: "form-control", placeholder: "Enter an instrument" %>
              </div>
            </div>
          </div>

          <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
            <%= submit_tag 'Post', class: 'btn btn-success', id: 'msgSubmit' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#selector').select2({
    //theme: "bootstrap"
    placeholder: "Select an instrument!"
  });
</script>

app/views/users/view_matches.html.erb
<ul class="matches">
  <% @matched_users.each do |user| %>
  <%# @matches.each do |m| %>
      <li>
        <%= user.name %> 
      </li>
  <% end %>
  
  <%= @statuses %>
</ul>